name: Terraform

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  terraform:
    name: Terraform
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Clean Terraform Cache
        run: rm -rf .terraform .terraform.lock.hcl terraform.tfstate terraform.tfstate.backup

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.14.0" # adjust with local version

      - name: Terraform Format
        run: terraform fmt -check

      - name: Terraform Init with upgrade
        run: terraform init --upgrade

      - name: Terraform Version
        run: terraform version

      - name: Terraform Validate
        run: terraform validate
